name: Tests and lints

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install dependencies
      run: |
        poetry install
    - name: Coverage and test with pytest
      run: |
        poetry run coverage run --source=steam_trade_bot --branch -m pytest tests/
        poetry run coverage report -m
    - name: Lint with pylint
      if: ${{ success() || failure() }}
      run: |
        poetry run pylint --rcfile pyproject.toml --fail-under 8 steam_trade_bot tests
    - name: Run mypy
      if: ${{ success() || failure() }}
      continue-on-error: true
      run: |
        poetry run mypy --ignore-missing-imports steam_trade_bot
    - name: Run black
      if: ${{ success() || failure() }}
      continue-on-error: true
      run: |
        poetry run black --check steam_trade_bot tests
